### ISSUE TITLE
append super hashcode and equals not working if the parent class is not in the same package

### ISSUE THREAD

**Issue by rtantsa** [maximeAudrain/jenerate#11]
Hello.
First of all, thank you for your great plugin.

I noticed that the append super checkbox for hashcode and equals can't be checked if the parent class is not in the same package. Is this the normal behaviour or may be a bug?

Thank you for your concern.

**Comment by maximeAudrain** [comment]
Dear Rtantsa,

Thank you for using the plugin :) 

Unfortunately I could not reproduce your problem: the "append super" checkbox is enabled with a superclass in the same package and in a different package .

For the "append super" checkbox to be enabled, you have to make sure that your class has a superclass which is not Object (here it should be the case) and the superclass should override both hashCode() and equals().

Please can you have a look if your superclass is implementing hashCode() and equals()? 

Cheers,

Maxime

**Comment by rtantsa** [comment]
Hello, thank you for you response.

Indeed, it works if the superclass is in an other package.
What I actually wanted to say is that the super can't be checked if the superclass is in an included jar (I think I wrote my issue too quickly, I'm sorry). Is this the normal behaviour or a bug?

Thanks.

**Comment by wenjiezhang2013** [comment]
I have the same problem, I installed the eclipse plugin, and my class has a super class, but when I use the plugin to generate the hashcode and equals, the `Append Super` is disabled.

![image](https://cloud.githubusercontent.com/assets/4951160/24582980/694a630c-16f1-11e7-90cb-6de76bb87c1e.png)

**Comment by maximeAudrain** [comment]
Hi,

Thanks for using the plugin!

I took a look at the source and to have the "append super" button enabled, you need the 3 conditions below valid:
- your current class superclass must not be the Object class.
- your current class superclass must have equals overridden explicitly
- your current class superclass must have hashcode overridden explicitly

Please make sure that those 3 conditions are fulfilled and let me know if the problem still occur afterward?

Cheers,

Maxime

**Comment by nnjeremy** [comment]
Hello,
I have the same problem. the super class is not the Object class and have equals and hashcode overridden explicitly. But the super class is a Maven Dependency.

Thanks for your help.

**Comment by helospark** [comment]
I have checked this.
The bug is caused by the [isEqualsOverriddenInClass method](https://github.com/maximeAudrain/jenerate/blob/ca573bfab47521aa75203f796cde4823d4ba8c7f/org.jenerate/src/java/org/jenerate/internal/ui/dialogs/factory/impl/EqualsHashCodeDialogFactory.java#L81).

It tries to find an `equals` method in the super class with a signature "QObject;", however in binary file (jars) the type references are resolved differently as per [documentation](https://help.eclipse.org/mars/index.jsp?topic=%2Forg.eclipse.jdt.doc.isv%2Freference%2Fapi%2Forg%2Feclipse%2Fjdt%2Fcore%2FSignature.html), so the "QObject;" is not the correct signature, instead it should be "Ljava.lang.Object".

A fix could be either to resolved the bindings in the class then the FQN can be checked for equality, however a simpler solution is to just convert the method signature (using `Signature.newTypeSignature(...)`) to the correct format before trying to find a method depending on the file-type (eg. using superclass.isBinary()).

@maximeAudrain I can open a PR if you are still maintaining this project.

**Comment by melloware** [comment]
I would say open a PR so when he gets to it or it may help others with similar issue!

**Comment by maximeAudrain** [comment]
Dear helospark, thanks for your debugging of this. I will try and have a look at this in the next days and deliver a fix. I'll keep you posted. Cheers

**Comment by helospark** [comment]
I have opened PR #16 

Note that this also fixes the "Append super" button, when (for some reason) fully qualified name is used for Object in the equals method.
Similarly both fixes are done for compareTo as well.

Please review and test if when you have the time.

**Comment by maximeAudrain** [comment]
Hi Helospark,

I just released the plugin in version 1.0.3 with your contribution. I tested and it looks good :) Thanks again for you help!

Cheers,

Maxime

**Comment by helospark** [comment]
@maximeAudrain Updated the plugin, it works great.

Thanks for the merge! :+1:
