### ISSUE TITLE
Optionally use Objects instead of MoreObjects

### ISSUE THREAD

**Issue by JanecekPetr** [maximeAudrain/jenerate#8]
As our company's application code is still on Java 6 (and probably won't migrate any time soon), we locked our Guava version to 17.0 as that is the last version that only counts with Java 6 and does not yet deprecate stuff because of Java 7.

Therefore, we don't have the MoreObjects class available to us and it woule be very helpful if Jenerate either found out by itself, or at least gave us the option to use Objects instead.

**Comment by maximeAudrain** [comment]
Dear JanecekPetr,

Thanks for using the plugin! I am quite busy those days but feel free to make a fork of the plugin, modify what you want and I will be happy to integrate your pull request!!

Otherwise, I will try to take a look in the following weeks but I cannot promise anything!

Cheers,

Maxime

**Comment by JanecekPetr** [comment]
6 years gone, hopefully nowadays nobody is still on Java 6. :)
